### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by anuj9196** [loadsys/metadata#1]
* [x] Bug

* CakePHP Version: 3.3.10
* Platform and Target: Linux (Ubuntu), Firefox Browser

### What I did
Installing Plugin to CakePHP 3.x

    cd plugins
    git clone git://github.com/joeytrapp/metadata.git

### What Happend

    Cloning into 'metadata'...
    fatal: remote error: 
      Repository not found.

### What is expected
To install plugin successfully

**Comment by justinyost** [comment]
This plugin is unmaintained and is not functional for CakePHP 3.x, sorry about that. I've added a note about the plugin being unmaintained to the description.
